export const BACKGROUND_FETCH_TASK = 'daily-affirmation-notification';
export const affirmations = [
    "I am worthy of love and respect",
    "I believe in my abilities",
    "I am proud of my accomplishments",
    "I am in control of my own happiness",
    "I am deserving of success",
    "I am strong and resilient",
    "I am surrounded by positivity",
    "I am constantly improving",
    "I trust my intuition",
    "I am open to new experiences",
    "I am capable of achieving my goals",
    "I am unique and valuable",
    "I am enough just as I am",
    "I am a work in progress",
    "I am a force for good",
    "I am a problem solver",
    "I am confident in my decisions",
    "I am grateful for my life",
    "I am a magnet for abundance",
    "I am at peace with my past",
    "I am growing every day",
    "I am a positive influence on others",
    "I am worthy of my dreams",
    "I am compassionate and understanding",
    "I am deserving of happiness",
    "I am confident in my skills",
    "I am an overcomer",
    "I am resourceful and adaptable",
    "I am kind to myself and others",
    "I am a great listener",
    "I am a creative thinker",
    "I am dedicated to my goals",
    "I am patient with my progress",
    "I am in charge of my destiny",
    "I am a loving and caring person",
    "I am an inspiration",
    "I am a powerful creator",
    "I am open to change and growth",
    "I am centered and balanced",
    "I am capable of facing challenges",
    "I am surrounded by love and support",
    "I am a good friend",
    "I am a role model",
    "I am focused on my purpose",
    "I am grateful for my body and mind",
    "I am committed to my wellbeing",
    "I am embracing my journey",
    "I am connected to my inner wisdom",
    "I am learning from my experiences",
    "I am deserving of all good things",
    "I am courageous and brave",
    "I am a skilled communicator",
    "I am connected to the present moment",
    "I am a beacon of light and love",
    "I am a conqueror of my fears",
    "I am a visionary",
    "I am on the path to greatness",
    "I am a master of my emotions",
    "I am a seeker of truth",
    "I am a healer",
    "I am vibrant and energetic",
    "I am unstoppable",
    "I am loved and appreciated",
    "I am in harmony with the universe",
    "I am a powerful manifestor",
    "I am grateful for every moment",
    "I am a leader",
    "I am embracing my authenticity",
    "I am the architect of my life",
    "I am at peace with myself and the world",
    "I am a force of positivity",
    "I am an achiever",
    "I am filled with gratitude and grace",
    "I am a magnet for success",
    "I am worthy of my own love and self-care",
    "I am a beacon of hope",
    "I am an explorer of life",
    "I am a lifelong learner",
    "I am a radiant being",
    "I am a catalyst for positive change",
    "I am an excellent decision-maker",
    "I am open to infinite possibilities",
    "I am deserving of joy and laughter",
    "I am a miracle worker",
    "I am balanced in mind, body and spirit",
    "I am a source of inspiration and motivation",
    "I am a lightworker",
    "I am on the path to self-discovery",
    "I am an example of courage and strength",
    "I am a peacemaker",
    "I am an innovator",
    "I am a blessing to those around me",
    "I am a reflection of divine love",
    "I am an emissary of peace",
    "I am an unstoppable force",
    "I am a co-creator of my reality",
    "I am a seeker of knowledge and wisdom",
    "I am a conduit for positive energy",
    "I am a master of my thoughts",
    "I am a beacon of serenity and tranquility",
    "I am an expression of love and light",
    "I am a symbol of hope and inspiration",
    "I am a vessel for positive transformation",
    "I am a guardian of my own happiness",
    "I am an embodiment of kindness and generosity"
];